# Generated by Django 4.2 on 2023-05-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icons')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Кольца'), (2, 'Ожерелья'), (3, 'Серьги'), (4, 'Брелки'), (5, 'Браслеты')])),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biser.jewelry')),
            ],
        ),
    ]
