# Generated by Django 4.2 on 2023-06-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biser', '0003_alter_order_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'ordering': ['-make_time'], 'verbose_name': 'Украшение', 'verbose_name_plural': 'Украшения'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-make_time'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AddField(
            model_name='jewelry',
            name='second_name',
            field=models.CharField(default='короткое описание', max_length=256, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Кольца'), (2, 'Ожерелья'), (3, 'Серьги'), (4, 'Брелки'), (5, 'Браслеты')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='icon',
            field=models.ImageField(upload_to='icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='make_time',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Время появления на сайте'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.FloatField(verbose_name='Цена в рублях'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарий к заказу'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='jewelry',
        ),
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='make_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=17, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='jewelry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biser.jewelry', verbose_name='Украшение'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='pictures', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='order',
            name='jewelry',
            field=models.ManyToManyField(related_name='all_jewelry', to='biser.jewelry', verbose_name='Украшения'),
        ),
    ]
