# Generated by Django 4.2 on 2023-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biser', '0005_order_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summ',
            field=models.FloatField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
